#training parameters
train:
  loss: "xentropy"       # must be either xentropy or iou
  max_epochs: 1000
  max_lr: 0.01          # sgd learning rate max
  min_lr: 0.01          # warmup initial learning rate
  up_epochs: 0           # warmup during first XX epochs (can be float)
  down_epochs:  0        # warmdown during second XX epochs  (can be float)
  max_momentum: 0.9      # sgd momentum max when lr is mim
  min_momentum: 0.9      # sgd momentum min when lr is max
  final_decay: 0.99      # learning rate decay per epoch after initial cycle (from min lr)
  w_decay: 0.00004       # weight decay
  batch_size:  1         # batch size
  report_batch: 1        # every x batches, report loss
  report_epoch: 1        # every x epochs, report validation set
  save_summary: False    # Summary of weight histograms for tensorboard
  save_imgs: True        # False doesn't save anything, True saves some 
                         # sample images (one per batch of the last calculated batch)
                         # in log folder
  avg_N: 1               # average the N best models
  crop_prop:
    height: 64
    width: 64 

# backbone parameters
backbone:
  name: "mobilenetv2"
  dropout: 0.0
  bn_d: 0.01
  OS: 8  # output stride
  train: True # train backbone?
  extra:
    width_mult: 1.0
    shallow_feats: True # get features before the last layer (mn2)

decoder:
  name: "aspp_residual_attention"
  dropout: 0.0
  bn_d: 0.01
  train: True # train decoder?
  extra:
    aspp_channels: 64
    skip_os: [4, 2]
    last_channels: 32

# classification head parameters
head:
  name: "segmentation"
  dropout: 0.0

# dataset (to find parser)
dataset:
  name: "onion"
  location: "/home/paperspace/Downloads/proj/onion/"
  workers: 2  # number of threads to get data
  img_means: #rgb
    - 0.40302554
    - 0.40815613
    - 0.38042293
  img_stds: #rgb
    - 0.23028688
    - 0.23069929
    - 0.21298651
  img_prop:
    width: 256
    height: 256
    depth: 3
  labels:
    0 : 'background'
    1 : 'Onion'
    2 : 'Weed'
    3 : 'void'
  labels_w:
    0 : 1.7859
    1 : 50.4983 
    2 : 50.4983
    3 : 0.0
  color_map: # bgr
    0 : [0,0,0]
    1 : [0,0,128]
    2 : [0,128,0]
    3 : [255,255,255]
